[project]
name = "cartegories"
version = "2.0.0"
description = "A mobile category game for the car."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.128.0",
]
